# Generated by Django 5.2.11 on 2026-02-23 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Por Pagar'), ('PARCIAL', 'Abono Parcial'), ('REVISION', 'En Revisión (Pagos Reportados)'), ('PAGADO', 'Pagado Totalmente')], default='PENDIENTE', max_length=15)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Base (Dueño Conductor)')),
                ('monto_chofer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio con Avance/Chofer')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=36.0, max_digits=10, verbose_name='Tasa BCV')),
                ('nombre_linea', models.CharField(default='Línea de Conductores Unidos', max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_factura', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='facturas_gastos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('ZELLE', 'Zelle / Divisas Digitales'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares (Bs.)'), ('USD', 'Dólares ($)')], default='BS', max_length=3)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=100)),
                ('cedula_rif', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.avisocobro')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=50)),
                ('comprobante', models.ImageField(upload_to='comprobantes/')),
                ('monto_bolivares', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_bcv_usada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('monto_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='REVISION', max_length=15)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.avisocobro')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Socio (Dueño)')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('unidad', models.CharField(help_text='Número de unidad/autobús', max_length=10, unique=True)),
                ('tiene_avance', models.BooleanField(default=False, help_text='Marcar si la unidad es trabajada por un chofer (Avance)', verbose_name='¿Tiene Avance Asignado?')),
                ('nombre_avance', models.CharField(blank=True, help_text='Opcional. Solo informativo.', max_length=100, null=True, verbose_name='Nombre del Avance')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avisocobro',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='core.socio'),
        ),
        migrations.AlterUniqueTogether(
            name='avisocobro',
            unique_together={('socio', 'mes', 'anio')},
        ),
    ]
