# Generated by Django 5.2.11 on 2026-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='clave_cambiada',
            field=models.BooleanField(default=False),
        ),
    ]
