# Generated by Django 5.2.11 on 2026-02-24 13:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cierremes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptocobro',
            name='monto_chofer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Precio con Avance/Chofer'),
        ),
        migrations.AlterField(
            model_name='conceptocobro',
            name='monto_sugerido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Precio Base (Dueño Conductor)'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=4, default=Decimal('36.0000'), max_digits=20, verbose_name='Tasa BCV'),
        ),
        migrations.AlterField(
            model_name='gastogeneral',
            name='monto_total_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historialtasa',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='itemaviso',
            name='monto_dolares',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_bolivares',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_dolares',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tasa_bcv_usada',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
