# Generated by Django 5.2.11 on 2026-02-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conceptocobro_monto_chofer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('APROBAR', 'Aprobación de Pago'), ('RECHAZAR', 'Rechazo de Pago'), ('CARGO_MANUAL', 'Cargo Manual Creado'), ('IMPORTACION', 'Importación de Excel'), ('CIERRE_MES', 'Cierre de Mes Contable')], max_length=20)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(help_text='Detalle de lo que se hizo y a quién afectó')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
