# Generated by Django 5.2.11 on 2026-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bitacoraauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraauditoria',
            name='accion',
            field=models.CharField(choices=[('APROBAR', 'Aprobación de Pago'), ('RECHAZAR', 'Rechazo de Pago'), ('CARGO_MANUAL', 'Cargo Manual Creado'), ('IMPORTACION', 'Importación de Excel'), ('ELIMINAR_METODO', 'Eliminación de Método de Pago'), ('CIERRE_MES', 'Cierre de Mes Contable')], max_length=20),
        ),
    ]
