# Generated by Django 5.2.11 on 2026-02-25 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bitacoraauditoria_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='codigo_verificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bitacoraauditoria',
            name='accion',
            field=models.CharField(choices=[('APROBAR', 'Aprobación de Pago'), ('RECHAZAR', 'Rechazo de Pago'), ('CARGO_MANUAL', 'Cargo Individual Creado'), ('CARGO_MASIVO', 'Generación Masiva (Formulario)'), ('GASTO_COLECTIVO', 'Distribución de Gasto Común'), ('IMPORTAR_CARGOS', 'Importación de Cargos (Excel)'), ('EDITAR_SOCIO', 'Edición de Datos de Socio'), ('IMPORTAR_SOCIOS', 'Importación de Socios (Excel)'), ('CIERRE_MES', 'Cierre de Periodo Contable'), ('ACTUALIZAR_METODO', 'Actualización de Método de Pago'), ('ELIMINAR_METODO', 'Eliminación de Método de Pago'), ('ACTUALIZAR_TASA', 'Actualización de Tasa Cambiaria')], max_length=20),
        ),
    ]
