# Generated by Django 5.2.11 on 2026-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260224_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsistema',
            name='dias_gracia',
            field=models.PositiveIntegerField(default=30, help_text='Días permitidos para tener deuda antes de bloquear el QR', verbose_name='Días de Gracia'),
        ),
    ]
